export const CERT_LIST_GET = "CERT_LIST_GET"
export const CERT_LIST_GET_FAIL = "CERT_LIST_GET_FAIL"
export const CERT_LIST_GET_SUCCESS = "CERT_LIST_GET_SUCCESS"
export const CERT_REDEEM = "CERT_REDEEM"
export const CERT_REDEEM_FAIL = "CERT_REDEEM_FAIL"
export const CERT_REDEEM_SUCCESS = "CERT_REDEEM_SUCCESS"

