export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_COMPLETE_REQUEST = 'ORDER_COMPLETE_REQUEST';
export const ORDER_COMPLETE_SUCCESS = 'ORDER_COMPLETE_SUCCESS';
export const ORDER_COMPLETE_FAIL = 'ORDER_COMPLETE_FAIL';
export const ORDER_COMPLETE_RESET = 'ORDER_COMPLETE_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_LIST_MY_SOLD_REQUEST = 'ORDER_LIST_MY_SOLD_REQUEST';
export const ORDER_LIST_MY_SOLD_SUCCESS = 'ORDER_LIST_MY_SOLD_SUCCESS';
export const ORDER_LIST_MY_SOLD_FAIL = 'ORDER_LIST_MY_SOLD_FAIL';
export const ORDER_LIST_MY_SOLD_RESET = 'ORDER_LIST_MY_SOLD_RESET';

export const ORDER_ARRANGE_REQUEST = 'ORDER_ARRANGE_REQUEST';
export const ORDER_ARRANGE_SUCCESS = 'ORDER_ARRANGE_SUCCESS';
export const ORDER_ARRANGE_FAIL = 'ORDER_ARRANGE_FAIL';
export const ORDER_ARRANGE_RESET = 'ORDER_ARRANGE_RESET';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const ORDER_PRODUCT_INFO = 'ORDER_PRODUCT_INFO';

export const ORDER_CREATE_REVIEW_REQUEST = 'ORDER_CREATE_REVIEW_REQUEST';
export const ORDER_CREATE_REVIEW_SUCCESS = 'ORDER_CREATE_REVIEW_SUCCESS';
export const ORDER_CREATE_REVIEW_FAIL = 'ORDER_CREATE_REVIEW_FAIL';
export const ORDER_CREATE_REVIEW_RESET = 'ORDER_CREATE_REVIEW_RESET';
